### ISSUE TITLE
[Enhancement] Use 7x7 values rather than 3x3 for better overall flatness

### ISSUE THREAD

**Issue by Tahx** [scottrini/OctoPrint-PrusaLevelingGuide#41]
Hello,

Thanks for this plugin, it's helping a lot.

However I had a really bad time getting a good first layer because of a convex bed (facing upwards) even when using the nylock mod.

Turns out that despites having great values within 0.01mm with the plugin when using 3x3, it will still cause issue because the plugin only use 3x3 values instead of 7x7 values.

Once switched to 7x7 values, I just can't get it better than 0.1mm over the whole bed...

So the issue is that when at some point I tighten one screw, it makes the bed to be lower where the screw is, and slighly higher around that screw, effectively causing bumps across the whole bed.

I was able to mitigate the effect by myself but that was pure guesswork and a lot of wasted times.

So if you have any plan to improve the plugin, then that's definitely something I'd suggest to.

Thanks.

**Comment by scottrini** [comment]
You can already do this currently with the plugin.  Just go into settings and change `G80 N3` to just `G80`.

I originally configured it so it enforces 3x3 since you only have those 8 points to adjust the bed (minus center).  If you remove the N3, it just uses whatever you have configured in the fw.
