### ISSUE TITLE
New install on Raspbery pi 3 b+ will not connect to prusa mk3 with plugin installed

### ISSUE THREAD

**Issue by mattfox27** [scottrini/OctoPrint-PrusaLevelingGuide#51]
Its wierd, brand new install with this plugin enabled it will not connect to prusa mk3, disable it and it connects fine

**Comment by scottrini** [comment]
Yeah, that is pretty weird...I just setup a brand new 3b+ with octoprint and this plugin for someone I gave a mk3s+ to earlier this week...no issues.  So this would definitely have to be unique to your setup, since there are many current users of the plugin without the issue.  I'd take a look at the unique combination of plugins you have installed.

**Comment by mattfox27** [comment]
I had to bump the serial connection timeouts up then it worked I guess it was just timing out to fast

**Comment by scottrini** [comment]
well, I'm glad you figured it out at least!  Happy printing!
