### ISSUE TITLE
Crash in to bed on MK3s with Bondtech

### ISSUE THREAD

**Issue by jymferrier** [scottrini/OctoPrint-PrusaLevelingGuide#7]
When using the modified bondtech firmware I am getting a crash on the second position check (nozzle presses on heat bed, forces calibration). Below are the notes from bondtech on what they changed in the firmware. Any thoughts?

#define CUSTOM_MENDEL_NAME "Bondtech-PE MK3s"

#define BONDTECH_MK3S

#define DEFAULT_AXIS_STEPS_PER_UNIT {100,100,3200/8,415}

#define TMC2130_USTEPS_E 16

#define Z_MAX_POS 205

#define LOAD_FILAMENT_1 "G1 E80 F400"

#define UNLOAD_FILAMENT_1 "G1 E-95 F7000"

#define FILAMENTCHANGE_FINALRETRACT -95

#define FILAMENTCHANGE_FIRSTFEED 80

#elif defined(BONDTECH_MK3S) current_position[E_AXIS] += 71; //Bondtech_V6 71mm from drive gear to melt zone

#elif defined(BONDTECH_MK3S) current_position[E_AXIS] -= 63; // Pull back 63mm, 8 mm below drive gear

#elif defined(BONDTECH_MK3S) current_position[E_AXIS] += 25.4f; //Bondtech MK2.5s 11 mm longer t melt zone

**Comment by scottrini** [comment]
This is unrelated to the plugin, but the issue is that your PINDA isn't firing when it's checking that point.  Your PINDA is too high.  You can confirm this by watching the PINDA on that point.  You'll see the red light on the back of the sensor doesn't turn off as it should.  Follow the Prusa steps for adjusting the height of the PINDA or print out that helper on thingiverse. (https://www.thingiverse.com/thing:1977997) yes it works for MK3S.  After that, re-run the full calibration and then you should be fine.

All of my MK3S printers are bear frame + bondtech (one is bondtech + mosquito) and I use custom firmware for them, but the custom firmware doesn't affect the mesh bed leveling.  The changes are for Z calibration and loading/unloading filament.
